"""Add is_draft column to Posts

Revision ID: 2b7f298ab4d8
Revises: b45cb2750325
Create Date: 2024-05-17 15:58:49.553793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7f298ab4d8'
down_revision = 'b45cb2750325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
