"""Added Posts table with answered column

Revision ID: ccd1acd52be5
Revises: 
Create Date: 2024-05-13 10:15:05.854113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd1acd52be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_column('answered')

    # ### end Alembic commands ###
