"""Added Posts table

Revision ID: 29073c2db901
Revises: c515e52ebd68
Create Date: 2024-05-13 00:12:34.543090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29073c2db901'
down_revision = 'c515e52ebd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    # ### end Alembic commands ###
